FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_APP_NAME
ARG VITE_REPOSITORY_URL
ARG VITE_NETBOX_URL
ARG VITE_NETBOX_TOKEN
ARG VITE_NETBOX_API_PREFIX
ARG VITE_STORAGE_KEY
ARG VITE_DEFAULT_VIEW
ARG VITE_AUTO_REFRESH
ARG VITE_REFRESH_INTERVAL_MS
ARG VITE_ENABLE_IP_GRAPH
ARG VITE_ENABLE_CIRCUITS
ENV VITE_APP_NAME=$VITE_APP_NAME \
	VITE_REPOSITORY_URL=$VITE_REPOSITORY_URL \
	VITE_NETBOX_URL=$VITE_NETBOX_URL \
	VITE_NETBOX_TOKEN=$VITE_NETBOX_TOKEN \
	VITE_NETBOX_API_PREFIX=$VITE_NETBOX_API_PREFIX \
	VITE_STORAGE_KEY=$VITE_STORAGE_KEY \
	VITE_DEFAULT_VIEW=$VITE_DEFAULT_VIEW \
	VITE_AUTO_REFRESH=$VITE_AUTO_REFRESH \
	VITE_REFRESH_INTERVAL_MS=$VITE_REFRESH_INTERVAL_MS \
	VITE_ENABLE_IP_GRAPH=$VITE_ENABLE_IP_GRAPH \
	VITE_ENABLE_CIRCUITS=$VITE_ENABLE_CIRCUITS
RUN npm run lint && npm run build

FROM nginx:1.27-alpine AS runtime
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 CMD wget --no-quiet --tries=1 --spider http://127.0.0.1/healthz || exit 1
