import { useMemo } from 'react'
import { Badge, Mono } from '../../app/ui'
import { colors, DeviceIcon, statusColor, roleName } from '../../app/theme'

export default function RackElevation({ rack, devices, onSelectDevice, selectedId }) {
  const height = rack.u_height || 42
  const occupied = useMemo(() => { const map = {}; devices.forEach(device => { if (device.position == null) return; const span = device.device_type?.u_height || 1; for (let offset = 0; offset < span; offset += 1) map[device.position + offset] = { device, span, top: offset === 0 } }); return map }, [devices])
  return <section style={{ marginBottom: 28 }}><header style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}><div><strong>{rack.name}</strong> <Badge>{devices.length} device{devices.length === 1 ? '' : 's'}</Badge></div><Mono style={{ color: colors.textDim, fontSize: 11 }}>{height}U</Mono></header><div style={{ position: 'relative', height: height * 20, background: '#0C1119', border: `1px solid ${colors.border}`, borderRadius: 6, padding: 3 }}>{Array.from({ length: height }, (_, index) => { const unit = height - index; const item = occupied[unit]; if (item && !item.top) return null; const device = item?.device; const color = device ? statusColor(device.status) : colors.border; return <div key={unit} onClick={() => device && onSelectDevice(device)} style={{ position: 'absolute', top: index * 20, left: 3, right: 3, height: (item?.span || 1) * 20 - 2, borderTop: device ? 0 : `1px dashed ${colors.border}`, border: device ? `1px solid ${selectedId === device.id ? color : colors.borderLight}` : undefined, borderLeft: device ? `3px solid ${color}` : undefined, background: device ? colors.panelAlt : 'transparent', display: 'flex', alignItems: 'center', gap: 7, padding: '0 8px', cursor: device ? 'pointer' : 'default' }}><span style={{ color: colors.textDim, fontSize: 9 }}>{device ? <><DeviceIcon role={roleName(device)} color={color} /><Mono style={{ marginLeft: 6 }}>{device.name}</Mono></> : unit}</span>{device && <Mono style={{ marginLeft: 'auto', color: colors.textDim, fontSize: 10 }}>{item.span}U</Mono>}</div> })}</div></section>
}
